sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t jldocker954/react-test -f ./client/dockerfile.dev ./client

script:
    - docker run jldocker954/react-test npm test -- --coverage

after_success:
    - docker build -t jldocker954/multi-client ./client
    - docker build -t jldocker954/multi-nginx ./nginx
    - docker build -t jldocker954/multi-server ./server
    - docker build -t jldocker954/multi-worker ./worker
    # login in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push jldocker954/multi-client
    - docker push jldocker954/multi-nginx 
    - docker push jldocker954/multi-server
    - docker push jldocker954/multi-worker 

deploy:
    provider: elasticbeantalk
    region: 'us-east-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-us-east-1-512636610551'
    bucket_path: 'docker-multi'
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    
    